name: Auto-Merge Develop to Main

on:
  push:
    branches:
      - develop

permissions:
  contents: write

jobs:
  test-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "22"
          distribution: "temurin"

      - name: Run tests
        run: mvn clean test checkstyle:check

      - name: Merge develop into main
        if: success()
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git fetch origin main
          git checkout main
          git merge origin/develop --no-edit
          git push origin main
