name: Auto PR from develop to main

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: "22"
          distribution: "temurin"

      - name: Run tests
        run: mvn clean test checkstyle:check

      - name: Create or update pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Automated PR: Promote develop to main"
          body: |
            This PR was created automatically after all tests passed on develop.
          base: main
          branch: develop
          draft: false
