name: CI - Build & Test

on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:
    branches:
      - main
      - "feature/**"

jobs:
  test:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/feature/') || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: "22"
          distribution: "temurin"

      - name: Build and run tests
        run: mvn clean test checkstyle:check

  build-and-deliver:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: "22"
          distribution: "temurin"

      - name: Build package
        run: mvn clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: TicTacSLT-jar
          path: target/*.jar
