name: Create PR Develop to Main - Automated Workflow
# This workflow runs on pushes to the develop branch, runs tests, and creates a pull request

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  test-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: "22"
          distribution: "temurin"

      - name: Run tests
        run: mvn clean test checkstyle:check

      - name: Create or update Pull Request to main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Automated PR: Promote develop to main"
          body: |
            This pull request was automatically created by CI after all tests passed on develop.

            Please review and merge when ready.
          base: main
          branch: develop
          draft: false
