name: Release - Build and Deliver

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "22"
          distribution: "temurin"

      - run: mvn clean package

      - uses: actions/upload-artifact@v3
        with:
          name: TicTacSLT-jar
          path: target/*.jar
